[project]
name = "backend"
version = "0.1.0"
description = "Backend API OpenRouter"
authors = [
    { name = "sidneysimas", email = "analistaemti@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "bcrypt>=5.0.0",
    "fastapi>=0.141.1",
    "psycopg2-binary>=2.9.9",
    "pyjwt>=2.14.0",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "sqlalchemy>=2.0.54",
    "uvicorn>=0.53.0",
]

[project.scripts]
backend = "main:app"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
